version: '3.7'

services:
  zookeeper:
    image: 'bitnami/zookeeper:3'
    ports:
     - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka1:
    image: 'bitnami/kafka:2'
    ports:
      - '9092:9092'
      - '19092:9092'
    environment:
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka1:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - 'kafka2_data:/bitnami'
    depends_on:
      - zookeeper
  kafka2:
    image: 'bitnami/kafka:2'
    ports:
      - '29092:9092'
    environment:
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka2:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - 'kafka_data:/bitnami'
    depends_on:
      - zookeeper
  kafka3:
    image: 'bitnami/kafka:2'
    ports:
      - '39092:9092'
    environment:
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka3:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - 'kafka3_data:/bitnami'
    depends_on:
      - zookeeper

volumes:
  kafka_data:
    driver: local
  kafka2_data:
    driver: local
  kafka3_data:
    driver: local
